const paths = {
    home: "/",
    about: "/about",
    contact: "/contact",
    shop: "/shop",
    shopDetail: "/shop/[shopId]",
    combo: "/combo",
    news: "/news",
    newsDetail: "/news/[newsId]",
    cart: "/cart",
    checkOut: "/checkout",
    login: "/login",
    user: "/user",
    wallet: "/user/wallet",
    agent: "/user/agent",
    profile: "/user/profile",
    setting: "/user/setting",
    bill: "/user/bill",
    gtable: "/user/gtable",
    order: "/user/order",
    payment: "/user/payment",
    signin: "/signin",
    withdraw: "/user/withdraw",
    transfer: "/user/transfer",
    userCart: "/user/cart",
    userCheckOut: "/user/checkout",
};

export default paths;
